{{- $release := .Release -}}
{{- $secret_name := "credentials" -}}
{{- range .Values.secrets_list }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type | default "Opaque" }}
data:
  {{- $old_secret := lookup "v1" "Secret" $release.Namespace $secret_name }}
  {{- if or (not $old_secret) (not $old_secret.data) }}
  mongodb-root-password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  mongodb-root-password: {{ index $old_secret.data "mongodb-root-password" }}
  {{ end }}
---
{{- end }}