apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: http
  selector:
    name: database
---
apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    name: node
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    name: node